tasks:
  - name: install protoc
    command: sudo apt install -y protobuf-compiler 

gitConfig:
  alias.st: status
  alias.cm: commit

vscode:
  extensions:
    - golang.go
    - zxh404.vscode-proto3
